name: Build pr
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - edited
      - synchronize
    branches:
      - main

jobs:
  build:
    name: Build and test
    runs-on: [self-hosted, dioxus, linux]
    container:
      image: jacekmultan/meal-planner-rust:0.4.1
      options: --user 1000
    env:
      HOME: /home/developer
      RUSTUP_HOME: /home/developer/.rustup
      CARGO_HOME: /home/developer/.cargo
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: whoami
        run: whoami
      - name: path
        run: echo $PATH
      - name: rustup
        run: |
          echo "HOME=$HOME"
          echo "RUSTUP_HOME=$RUSTUP_HOME"
          echo "CARGO_HOME=$CARGO_HOME"
      - name: Check
        run: cargo check --workspace --all-targets --verbose
      - name: Clippy
        run: cargo clippy --workspace --all-targets -- -D warnings
      - name: Test
        run: cargo test --workspace --all-targets --features test-utils
      - name: Format
        run: cargo fmt --all -- --check
      - name: cargo metadata
        run: cargo metadata
      - name: build dioxus linux app
        run: dx build --platform linux -p meal-planner-app
      - name: build dioxus android app
        run: dx build --platform android -p meal-planner-app
      - name: build dioxus web app
        run: dx build --platform web -p meal-planner-app

  build-windows:
    name: Build Windows App
    runs-on: [self-hosted, dioxus, windows]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: metadata
        run: cargo metadata
      - name: build dioxus windows app
        run: dx build --platform windows -p meal-planner-app

