name: Build pr
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - edited
      - synchronize
    branches:
      - main

jobs:
  build:
    name: Build and test
    runs-on: [self-hosted, dioxus, linux]
    container:
      image: jacekmultan/meal-planner-rust:0.4.5
      options: --user 1000
    env:
      HOME: /home/developer
      RUSTUP_HOME: /home/developer/.rustup
      CARGO_HOME: /home/developer/.cargo
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check
        run: cargo check --workspace --all-targets --verbose
      - name: Clippy
        run: cargo clippy --workspace --all-targets -- -D warnings
      - name: Test
        run: cargo test --workspace --all-targets --features test-utils
      - name: Format
        run: cargo fmt --all -- --check
      - name: build WASM worker
        run: cargo build -p meal-planner-lib --bin wasm_worker_main --features __internal-wasm-worker-bin --target wasm32-unknown-unknown --release
      - name: pack WASM worker
        run: wasm-bindgen --target web --out-dir pkg-worker target/wasm32-unknown-unknown/release/wasm_worker_main.wasm 
      - name: cargo metadata
        run: cargo metadata
      - name: build dioxus linux app
        run: dx build --platform linux -p meal-planner-app
      - name: build dioxus android app
        run: dx build --platform android -p meal-planner-app
      - name: build dioxus web app
        run: dx build --platform web -p meal-planner-app

# disable for now because starting playwright tests is unstable
  playwright-tests:
    timeout-minutes: 60
    runs-on: [self-hosted, dioxus, linux]
    container:
      image: jacekmultan/meal-planner-rust:0.4.3
      options: --user 1000
    env:
      HOME: /home/developer
      RUSTUP_HOME: /home/developer/.rustup
      CARGO_HOME: /home/developer/.cargo
    needs: [build]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: cargo metadata
      run: cargo metadata
    - name: build dioxus web app
      run: dx build --platform web -p meal-planner-app
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Install dependencies
      run: npm ci
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

  build-windows:
    name: Build Windows App
    runs-on: [self-hosted, dioxus, windows]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: metadata
        run: cargo metadata
      - name: build dioxus windows app
        run: dx build --platform windows -p meal-planner-app

